### PR TITLE
Fix using colors in table

### LINKED ISSUE #6: How to add colour
I'm having issues adding color to cells and am wondering what you would recommend.

```rust
    use colored::*;
    let mut table = term_table::Table::new();
    table.style = term_table::TableStyle::thin();
    table.add_row(Row::new(vec![
        TableCell::new("one".red().bold()),
        TableCell::new("two".red().bold()),
    ]));
    table.add_row(Row::new(vec![
        TableCell::new("three".red()),
        TableCell::new("four".red()),
    ]));
    println!("{}", table.render());
```

Prints:

image

I'm assuming it has to do with the len of the string is not the display width because of the escape codes added for the coloured output. I don't see anything in term-table-rs that can handle colour, so I'm wondering how you would recommend adding colour to cells (or if it can reliably be done with term-table-rs)?

### PR DESCRIPTION
**Pull request by RRethy**
I believe the issue is in [`TableCell::wrapped_content`](https://github.com/RyanBluth/term-table-rs/blob/d81331944f4b8c4bbac7435cd4921733e5b45e64/src/table_cell.rs#L125-L138), we are looping over each char to see if content should be wrapped, but for escape sequences, each char may not display in the terminal. Still pondering how best to fix this, open to suggestions and edits.

Just realized rust formatter changed some stuff, i'll revert that later to minimize the diff, this commit only adds a basic test I used for debugging.

Closes #6

### CODE REVIEW

**Comment by RyanBluth** [comment]
In `TableCell::wrapped_content` I add `\0` if the cell shouldn't be padded. I wonder if this could be messing up the escape codes? Just a guess. 

`STRIP_ANSI_RE` is supposed to strip out escape codes for checking string length but it doesn't look like it's being used in `TableCell::wrapped_content`. Just another observation

**Comment by RRethy** [comment]
I think it's the latter since `self.pad_content` is true. We'll probably need using `STRIP_ANSI_RE` since that's what `TableCell::width` uses to get the correct width. Maybe getting the indices of the escapes codes using `STRIP_ANSI_RE` then when we iterate, if the char we are on is in an escape code range (matched previously), just push it onto `buf` and keep going. Will try an implementation tmrw.

File: src/table_cell.rs [hunk 1]
```diff
@@ -119,22 +120,29 @@ impl<'data> TableCell<'data> {
...
                 buf.push(pad_char);
-                if c.1 == '\n' {
+                if c == '\n' {
+                    byte_index += 1;
                     continue;
                 }
             }
-            buf.push(c.1);
+            byte_index += c.len_utf8();
+            buf.push(c);
```
Comment (RRethy) [inline src/table_cell.rs:145]: This is the fix rn. It gets the indices that contain escape codes and treats them as 0 width characters by always pushing them onto `buf`. We have to track `byte_index` since `match_iter` will return byte indices and we may iterate over multibyte chars.

File: src/lib.rs [hunk 2]
```diff
@@ -1128,6 +1124,18 @@ r"+-----------------------------------------------------------------------------
...
+        let mut table = Table::new();
+        table.add_row(Row::new(vec![TableCell::new("\x1b[31ma\x1b[0m")]));
+        let expected = "╔═══╗
+║ \u{005c}u{1b}[31ma\\u{1b}[0m ║
+╚═══╝
+";
+        println!("{}", table.render());
+        assert_eq!(expected, table.render());
+    }
+
```
Comment (RRethy) [inline src/lib.rs:1138]: Right now this test fails even though the printed output looks as expected.

```
---- test::colored_data_works stdout ----
╔═══╗
║ a ║
╚═══╝

thread 'test::colored_data_works' panicked at 'assertion failed: `(left == right)`

Diff < left / right > :
<"╔═══╗\n║ \\u{1b}[31ma\\u{1b}[0m ║\n╚═══╝\n"
>"╔═══╗\n║ \u{1b}[31ma\u{1b}[0m ║\n╚═══╝\n"
```

I can't figure out how to get the expected text to only show a single backslash, `assert_eq` is doing some funky escaping. Here is what I've tried:

1. `\u{005c}` prints `\\`
2. `\\` prints `\\`
3. `\` prints `\\`
4. `r"\"` also prints `\\`

**Comment by RRethy** [comment]
Tests are passing.

File: src/lib.rs [hunk 3]
```diff
@@ -1128,6 +1124,18 @@ r"+-----------------------------------------------------------------------------
...
     }
 
+    #[test]
+    fn colored_data_works() {
+        let mut table = Table::new();
+        table.add_row(Row::new(vec![TableCell::new("\x1b[31ma\x1b[0m")]));
+        let expected = "╔═══╗
+║ \u{1b}[31ma\u{1b}[0m ║
+╚═══╝
+";
```
Comment (RRethy) [inline src/lib.rs:1134]: image

**Comment by RyanBluth** [comment]
Looks good to me. I will merge this and do some testing in a couple days. If everything checks out then I'll do a release with your fix. Thanks!

**Comment by RRethy** [comment]
Sweet! Thanks for the cool crate mate 👍
